spring.application.name=codecleaner

spring.datasource.url=jdbc:postgresql://localhost:5432/codecleaner
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN